version: "3.8"

services:
  hero-postgres:
    image: postgres:16
    container_name: hero_db
    environment:
      POSTGRES_DB: herodb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - hero_pgdata:/var/lib/postgresql/data
  monster-postgres:
    image: postgres:16
    container_name: monster_db
    environment:
      POSTGRES_DB: monster_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - monster_pgdata:/var/lib/postgresql/data

volumes:
  hero_pgdata:
  monster_pgdata:
