version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: hero_db
    environment:
      POSTGRES_DB: herodb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
